-- ============================================================================
-- Mano Mobile — one invoice, many kinds of line
--
-- A customer collecting a repaired phone buys a tempered glass and a cover at
-- the same counter, in the same minute, and walked out with two invoices —
-- because the repair and the accessories were two screens with two "Complete
-- Sale" buttons. This lets the repair checkout carry products, and gives the
-- invoice a place to say what each line was.
--
-- ── Why lines under `sales`, not a new `invoices` table ─────────────────────
-- `sales` already is the invoice header: one row per invoice number drawn from
-- invoice_no_seq, with the customer, the dealer, the credit account, the total
-- and what was paid. When it was written it deliberately had no lines table —
-- "nothing currently asks" (20260901000011). This is the thing that asks.
-- Adding the lines beneath the header that exists is one join for the screens
-- that want detail and no change at all for the many that only want a total.
--
-- ── What `line_items` still does ────────────────────────────────────────────
-- sales.line_items (jsonb) stays exactly as it is: the minimal
-- {"type":"accessory","id","qty"} list that void_sale() restocks from. The
-- repair checkout writes it too, so voiding a combined invoice puts the
-- accessories back on the shelf the same way voiding an accessory sale does.
-- sale_items is the rich description for people; line_items is the terse one
-- for the restock function. Two shapes, two readers, both written at once.
--
-- ── kind ────────────────────────────────────────────────────────────────────
--   repair_service  the repair charge for one job (reference_id = RM-nnn)
--   repair_part     a part billed to the customer for that job
--   accessory       a product from accessory_products (reference_id = its id)
--   sim / reload    for the day the counter sells those through the same bill
--   other           anything typed in by hand
-- ============================================================================

do $$ begin
  create type sale_item_kind as enum
    ('repair_service', 'repair_part', 'accessory', 'sim', 'reload', 'other');
exception when duplicate_object then null; end $$;

create table if not exists public.sale_items (
  id            bigint generated by default as identity primary key,
  sale_id       uuid not null references public.sales (id) on delete cascade,
  -- Denormalised from the header. The invoice number is what every screen
  -- and every printed page already holds, so the lines are looked up by it
  -- without first fetching the header to learn its uuid.
  invoice_no    text not null,
  kind          sale_item_kind not null,
  -- RM-nnn for a repair line, the accessory_products id for a product, null
  -- for a hand-typed line. Text, because the two are different types and the
  -- job id is the one that gets quoted.
  reference_id  text,
  description   text not null,
  qty           integer not null default 1 check (qty > 0),
  unit_price    numeric(12,2) not null default 0,
  discount      numeric(12,2) not null default 0 check (discount >= 0),
  -- Stored, not computed: it is what was printed, and if unit_price were ever
  -- corrected later the paper the customer holds would not change with it.
  line_total    numeric(12,2) not null default 0,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

comment on table public.sale_items is
  'The lines of an invoice. One row per repair charge, part, accessory or other item billed on a sale; the header is public.sales.';

create index if not exists sale_items_sale_idx    on public.sale_items (sale_id);
create index if not exists sale_items_invoice_idx on public.sale_items (invoice_no);
create index if not exists sale_items_kind_idx    on public.sale_items (kind);

-- ── Row Level Security — the same door as the header ────────────────────────
alter table public.sale_items enable row level security;

drop policy if exists sale_items_select on public.sale_items;
create policy sale_items_select on public.sale_items
  for select to authenticated
  using (public.is_staff() and public.module_can_read('Sales / POS'));

drop policy if exists sale_items_insert on public.sale_items;
create policy sale_items_insert on public.sale_items
  for insert to authenticated
  with check (public.is_staff() and public.module_can_write('Sales / POS'));

-- Deliberately no update or delete policy. A line on an invoice the customer
-- has walked out with is history; voiding the sale is how it is undone, and
-- the cascade from sales(id) is how the lines go with it.
