-- ============================================================================
-- Mano Mobile — Main Category → Subcategory for the accessory catalogue
--
-- Every accessory type was one flat "category" (Chargers, Cables, Cases…),
-- which made "Type-C Charger" and "Lightning Charger" either two separate
-- main categories (the list balloons as the shop stocks more variants) or
-- indistinguishable within one. This adds one more level: a subcategory
-- belongs to exactly one main category (accessory_categories), and the
-- product form's picker narrows to just that category's subcategories once
-- one is chosen.
--
-- Deliberately still two levels, not N: connector type, wattage, colour and
-- similar specs are product attributes, not more category depth — cramming
-- them in here would recreate the "one category per variant" problem this
-- migration exists to fix, one level down instead of at the top.
-- ============================================================================

create table if not exists public.accessory_subcategories (
  id          bigint generated by default as identity primary key,
  category_id bigint not null references public.accessory_categories (id) on delete cascade,
  name        text not null,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

comment on table public.accessory_subcategories is
  'One level under accessory_categories, e.g. category "Chargers" -> subcategories "Type-C", "Micro USB", "Lightning".';

-- Unique within its own category, not globally — "Type-C" can reasonably
-- exist under both Chargers and Cables as two different subcategory rows.
create unique index if not exists accessory_subcategories_name_key
  on public.accessory_subcategories (category_id, lower(name));
create index if not exists accessory_subcategories_category_idx
  on public.accessory_subcategories (category_id);

alter table public.accessory_products add column if not exists subcategory text not null default '';

comment on column public.accessory_products.subcategory is
  'Denormalized subcategory label — same reasoning as brand/category/supplier: a historic product keeps its label even if the subcategory is later renamed or deactivated.';

-- ── Row Level Security — same shape as accessory_categories ────────────────

alter table public.accessory_subcategories enable row level security;

drop policy if exists accessory_subcategories_select on public.accessory_subcategories;
create policy accessory_subcategories_select on public.accessory_subcategories
  for select to authenticated using (public.is_staff());

drop policy if exists accessory_subcategories_write on public.accessory_subcategories;
create policy accessory_subcategories_write on public.accessory_subcategories
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));
