-- ============================================================================
-- Mano Mobile — barcode label templates
--
-- The shop prints several different labels off one printer: the product
-- barcode, the repair job tag, the spare-part label. Until now there was one
-- global set of barcode settings held in memory, so changing the bar height
-- for a product label also changed it for every other label — and the whole
-- lot reset on refresh.
--
-- A template is one saved label design: which layout renders it, the barcode
-- format and bar geometry, and the physical stock size it is cut for. One
-- template is the default, which is what the app falls back to.
--
-- 'Standard' is seeded below with exactly the settings the app has been using,
-- so nothing about the current labels changes when this runs.
-- ============================================================================

-- ── Enums ───────────────────────────────────────────────────────────────────

do $$ begin
  -- Which renderer draws the label. Mirrors BarcodeLabelModal's `variant`:
  -- adding a new design means a new value here and a new branch there.
  create type barcode_layout as enum ('simple', 'repair', 'part');
exception when duplicate_object then null; end $$;

do $$ begin
  create type barcode_format as enum ('CODE128', 'CODE39', 'EAN13');
exception when duplicate_object then null; end $$;

-- ── Templates ───────────────────────────────────────────────────────────────

create table if not exists public.barcode_templates (
  id              bigint generated by default as identity primary key,
  -- Unique so the picker can never show two identically named designs, which
  -- is the one thing that makes "which template did I print?" unanswerable.
  name            text not null unique,
  layout          barcode_layout not null default 'simple',

  format          barcode_format not null default 'CODE128',
  -- react-barcode's `width` is a module multiplier, not pixels, and accepts
  -- fractions — the auto-fit shrink in BarcodeLabelModal lands on values like
  -- 1.7, so this cannot be an integer.
  bar_width       numeric(4,2) not null default 2    check (bar_width > 0),
  bar_height      integer      not null default 60   check (bar_height > 0),
  font_size       integer      not null default 12   check (font_size > 0),
  show_text       boolean      not null default true,
  code_prefix     text         not null default 'MM',

  -- Physical stock the design is cut for.
  label_width_mm  numeric(6,2) not null default 50   check (label_width_mm > 0),
  label_height_mm numeric(6,2) not null default 25   check (label_height_mm > 0),
  label_margin_mm numeric(4,2) not null default 3    check (label_margin_mm >= 0),

  is_default      boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  created_by      uuid references auth.users (id) on delete set null
);

-- At most one default. A partial unique index rather than a trigger: the
-- database refuses a second default outright instead of quietly fixing it up.
create unique index if not exists barcode_templates_one_default
  on public.barcode_templates (is_default) where is_default;

drop trigger if exists trg_barcode_templates_touch on public.barcode_templates;
create trigger trg_barcode_templates_touch
  before update on public.barcode_templates
  for each row execute function public.touch_updated_at();

-- ── Switching the default ───────────────────────────────────────────────────
-- Two statements that must not be seen apart: clearing the old default and
-- setting the new one. Done from the client they would momentarily leave zero
-- defaults, or trip the unique index if ordered the other way.

create or replace function public.set_default_barcode_template(p_id bigint)
returns public.barcode_templates
language plpgsql
security definer
set search_path = public
as $$
declare
  tpl public.barcode_templates;
begin
  if not public.has_role('Admin'::staff_role, 'Cashier'::staff_role) then
    raise exception 'Not authorised to change the default label template';
  end if;

  update public.barcode_templates set is_default = false
   where is_default and id <> p_id;

  update public.barcode_templates set is_default = true
   where id = p_id
  returning * into tpl;

  if not found then
    raise exception 'Barcode template % not found', p_id;
  end if;

  return tpl;
end $$;

-- ── The current design, saved as a template ─────────────────────────────────
-- These are exactly the values INITIAL_BARCODE has been using, so seeding it
-- changes nothing about what prints today.

insert into public.barcode_templates
  (name, layout, format, bar_width, bar_height, font_size, show_text,
   code_prefix, label_width_mm, label_height_mm, label_margin_mm, is_default)
values
  ('Standard', 'simple', 'CODE128', 2, 60, 12, true, 'MM', 50, 25, 3, true)
on conflict (name) do nothing;

-- The repair tag already pins itself to 50 x 25 in code; recorded here so it
-- shows up in the picker alongside the others rather than being invisible.
insert into public.barcode_templates
  (name, layout, format, bar_width, bar_height, font_size, show_text,
   code_prefix, label_width_mm, label_height_mm, label_margin_mm, is_default)
values
  ('Repair Job Tag', 'repair', 'CODE128', 2, 42, 12, false, 'RM', 50, 25, 2, false)
on conflict (name) do nothing;

-- ── Row level security ──────────────────────────────────────────────────────

alter table public.barcode_templates enable row level security;

-- Everyone printing a label needs to read them.
drop policy if exists barcode_templates_select on public.barcode_templates;
create policy barcode_templates_select on public.barcode_templates
  for select to authenticated using (public.is_staff());

drop policy if exists barcode_templates_write on public.barcode_templates;
create policy barcode_templates_write on public.barcode_templates
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));

comment on table public.barcode_templates is
  'Saved label designs. One row is is_default and is what the app loads at startup; layout picks which renderer draws it.';
