-- ============================================================================
-- Mano Mobile — selling a phone under its minimum price, on the record
--
-- sell_mobile_sale() (20260924000059 / 20260927000060) refused any device
-- priced below its min_selling_price. That is too strict for a real counter:
-- sometimes a phone has to go for less — an old unit, a regular customer, a
-- price war down the road. Refusing the sale just pushes it off the system.
--
-- So it is allowed now, but never silently:
--   * the cashier must give a reason, or the sale is refused as before;
--   * every device sold under its minimum gets a line in the
--     "Below-Minimum Sales" account (device_below_min_sales): which phone,
--     the minimum, what it actually sold for, the shortfall, why, and who;
--   * v_below_min_sales is that account for reporting — voided invoices drop
--     out of it automatically, so a cancelled sale never counts as a loss.
--
-- The shortfall is (minimum − sold price): money the shop chose not to take
-- against its own floor. Reports > Below Min totals and analyses it.
-- ============================================================================

create table if not exists public.device_below_min_sales (
  id           bigint generated by default as identity primary key,
  invoice_no   text not null,
  device_id    bigint references public.mobile_devices (id) on delete set null,
  imei         text not null,
  device_name  text not null,
  brand        text not null default '',
  buying_price numeric(12,2) not null default 0,
  min_price    numeric(12,2) not null,
  sold_price   numeric(12,2) not null,
  -- Stored rather than computed so the line reads exactly as it was booked.
  shortfall    numeric(12,2) not null check (shortfall > 0),
  reason       text not null check (btrim(reason) <> ''),
  cashier      text,
  created_by   uuid references auth.users (id) on delete set null,
  created_at   timestamptz not null default now()
);

create index if not exists device_below_min_sales_invoice_idx on public.device_below_min_sales (invoice_no);
create index if not exists device_below_min_sales_created_idx on public.device_below_min_sales (created_at desc);

comment on table public.device_below_min_sales is
  'The Below-Minimum Sales account: one line per device sold under its min_selling_price — the shortfall, the reason and the cashier. Written only by sell_mobile_sale().';

alter table public.device_below_min_sales enable row level security;

drop policy if exists device_below_min_sales_select on public.device_below_min_sales;
create policy device_below_min_sales_select on public.device_below_min_sales
  for select to authenticated using (public.is_staff());
-- No insert/update/delete policy: written only inside sell_mobile_sale().

-- Voided invoices excluded — a sale that never happened lost nothing.
create or replace view public.v_below_min_sales with (security_invoker = true) as
select b.*, s.sold_on, s.customer
  from public.device_below_min_sales b
  join public.sales s on s.invoice_no = b.invoice_no
 where s.status <> 'Voided';

grant select on public.v_below_min_sales to authenticated;

-- ── sell_mobile_sale, with a reason instead of a refusal ────────────────────

drop function if exists public.sell_mobile_sale(jsonb, jsonb);

create or replace function public.sell_mobile_sale(
  p_devices          jsonb,
  p_accessories      jsonb default '[]'::jsonb,
  p_below_min_reason text  default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  item     record;
  d        public.mobile_devices;
  v_no     text;
  v_below  boolean := false;
  v_reason text := nullif(btrim(coalesce(p_below_min_reason, '')), '');
  v_cashier text;
begin
  if not (public.is_staff() and public.module_can_write('Sales / POS')) then
    raise exception using errcode = '42501', message = 'Selling needs Sales / POS access.';
  end if;

  if p_devices is null or jsonb_typeof(p_devices) <> 'array' or jsonb_array_length(p_devices) = 0 then
    raise exception 'A mobile sale needs at least one device.';
  end if;

  for item in
    select (elem ->> 'id')::bigint as id, (elem ->> 'price')::numeric as price
    from jsonb_array_elements(p_devices) as elem
  loop
    if item.id is null or item.price is null or item.price < 0 then
      raise exception 'Invalid device line: %', item;
    end if;

    select * into d from public.mobile_devices where id = item.id for update;
    if not found then
      raise exception 'Device % is no longer in the inventory.', item.id;
    end if;
    if d.status = 'sold' then
      raise exception 'IMEI % (%) has already been sold on %.', d.imei, d.name, coalesce(d.sold_invoice_no, 'another invoice');
    end if;
    if d.status not in ('available', 'reserved') then
      raise exception 'IMEI % (%) is set aside to go back to the company and cannot be sold.', d.imei, d.name;
    end if;
    if d.min_selling_price > 0 and round(item.price, 2) < d.min_selling_price then
      v_below := true;
    end if;
  end loop;

  -- Below the floor is allowed, but only with a reason on the record.
  if v_below and v_reason is null then
    raise exception 'A device is priced below its minimum selling price — give a reason to sell it anyway.';
  end if;

  if p_accessories is not null and jsonb_typeof(p_accessories) = 'array' and jsonb_array_length(p_accessories) > 0 then
    perform public.sell_accessory_stock(p_accessories);
  end if;

  v_no := public.next_invoice_no();
  select full_name into v_cashier from public.profiles where id = auth.uid();

  for item in
    select (elem ->> 'id')::bigint as id, (elem ->> 'price')::numeric as price
    from jsonb_array_elements(p_devices) as elem
  loop
    select * into d from public.mobile_devices where id = item.id;

    if d.min_selling_price > 0 and round(item.price, 2) < d.min_selling_price then
      insert into public.device_below_min_sales (
        invoice_no, device_id, imei, device_name, brand, buying_price,
        min_price, sold_price, shortfall, reason, cashier, created_by
      ) values (
        v_no, d.id, d.imei, d.name, d.brand, d.buying_price,
        d.min_selling_price, round(item.price, 2), d.min_selling_price - round(item.price, 2),
        v_reason, v_cashier, auth.uid()
      );
    end if;

    update public.mobile_devices
       set status          = 'sold',
           sold_invoice_no = v_no,
           sold_price      = round(item.price, 2),
           sold_at         = now()
     where id = item.id;
  end loop;

  return v_no;
end $$;

comment on function public.sell_mobile_sale(jsonb, jsonb, text) is
  'Marks every device on a mobile sale sold, deducts its accessory stock, and returns the invoice number — one transaction. A device under its minimum price needs p_below_min_reason and is booked to device_below_min_sales.';

grant execute on function public.sell_mobile_sale(jsonb, jsonb, text) to authenticated;
