-- ============================================================================
-- Mano Mobile — accessory retail inventory and its sale-time stock deduction
--
-- Until now, none of this existed anywhere durable. InventoryManagement's
-- Accessories tab held its product list in a plain useState([]) — gone on
-- every refresh, invisible to every other browser — and AccessorySales kept
-- a SECOND, entirely separate useState([]) of its own that never synced with
-- the first. Neither ever wrote a database row, so a "sale" never actually
-- moved a real stock number anywhere.
--
-- This is deliberately separate from repair_parts (see that migration's own
-- comment): a screen protector sold at the counter and a screen consumed in
-- a repair are counted, costed and reordered differently.
--
--   accessory_categories / accessory_brands / accessory_suppliers
--     reference lists behind the Add/Edit Product form's cascading pickers
--   accessory_products
--     the catalogue itself — what's on the shelf, at what price
--     brand/category/supplier are stored as plain text on each row (not a
--     foreign key) so a historic product keeps its label even if the
--     category it once belonged to is later renamed or deleted — the same
--     choice already made for repair_jobs.dealer.
--   sell_accessory_stock()
--     the only way stock is ever deducted; see its own comment below
-- ============================================================================

-- ── Reference lists ─────────────────────────────────────────────────────────

create table if not exists public.accessory_categories (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);
create unique index if not exists accessory_categories_name_key on public.accessory_categories (lower(name));

create table if not exists public.accessory_brands (
  id           bigint generated by default as identity primary key,
  name         text not null,
  type         text not null default 'accessory' check (type in ('device', 'accessory', 'both')),
  -- Which accessory_categories this brand belongs to; empty means "all".
  category_ids bigint[] not null default '{}',
  created_at   timestamptz not null default now()
);
create unique index if not exists accessory_brands_name_key on public.accessory_brands (lower(name));

create table if not exists public.accessory_suppliers (
  id         bigint generated by default as identity primary key,
  name       text not null,
  phone      text not null default '',
  email      text not null default '',
  -- Which accessory_brands this supplier carries; empty means "all".
  brand_ids  bigint[] not null default '{}',
  created_at timestamptz not null default now()
);
create unique index if not exists accessory_suppliers_name_key on public.accessory_suppliers (lower(name));

-- ── The catalogue ───────────────────────────────────────────────────────────

create table if not exists public.accessory_products (
  id            bigint generated by default as identity primary key,
  -- e.g. SP-001, auto-generated client-side from the category abbreviation
  -- but editable, so unique rather than a computed column.
  code          text not null unique,
  name          text not null,
  brand         text not null default '',
  category      text not null default '',
  model         text not null default '',
  buying_price  numeric(12,2) not null default 0 check (buying_price >= 0),
  selling_price numeric(12,2) not null default 0 check (selling_price >= 0),
  stock         integer not null default 0 check (stock >= 0),
  min_stock     integer not null default 0 check (min_stock >= 0),
  supplier      text not null default '',
  added_date    date not null default current_date,
  -- Optional merchandising note shown to cashiers on the sales screen,
  -- e.g. "Popular add-on" — not a stock or pricing fact, just a tip.
  insight       text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  created_by    uuid references auth.users (id) on delete set null
);

create index if not exists accessory_products_category_idx on public.accessory_products (category);
create index if not exists accessory_products_brand_idx    on public.accessory_products (brand);

drop trigger if exists trg_accessory_products_touch on public.accessory_products;
create trigger trg_accessory_products_touch
  before update on public.accessory_products
  for each row execute function public.touch_updated_at();

-- ── Selling stock ────────────────────────────────────────────────────────────
-- A browser cannot safely do a cart's worth of read-modify-writes: two
-- cashiers checking out overlapping carts at the same moment could both read
-- stock 1 and both sell it. Looping the whole cart inside one function makes
-- it one transaction — the UPDATE ... WHERE stock >= qty pattern (same as
-- resolve_part_request) takes a row lock and fails the line if stock is
-- short, and because every line runs in the same transaction, one short line
-- rolls the *entire* sale back rather than selling five of six items and
-- quietly dropping the sixth.

create or replace function public.sell_accessory_stock(p_items jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item record;
begin
  if not public.is_staff() then
    raise exception 'Not authorised to sell accessories';
  end if;

  for item in
    select (elem ->> 'id')::bigint as id, (elem ->> 'qty')::integer as qty
    from jsonb_array_elements(p_items) as elem
  loop
    if item.id is null or item.qty is null or item.qty <= 0 then
      raise exception 'Invalid cart line: %', item;
    end if;

    update public.accessory_products
       set stock = stock - item.qty
     where id = item.id
       and stock >= item.qty;

    if not found then
      raise exception 'Not enough stock for product % (need %)', item.id, item.qty;
    end if;
  end loop;
end $$;

comment on function public.sell_accessory_stock(jsonb) is
  'Deducts stock for a whole cart in one transaction. p_items: [{"id": 12, "qty": 2}, ...]. Any line short on stock aborts the entire sale.';

-- ============================================================================
-- Row Level Security — all staff read, Admin/Cashier write (accessories are
-- sold and stocked at the counter; technicians neither manage nor sell them,
-- same split repair_parts uses).
-- ============================================================================

alter table public.accessory_categories enable row level security;
alter table public.accessory_brands     enable row level security;
alter table public.accessory_suppliers  enable row level security;
alter table public.accessory_products   enable row level security;

drop policy if exists accessory_categories_select on public.accessory_categories;
create policy accessory_categories_select on public.accessory_categories
  for select to authenticated using (public.is_staff());
drop policy if exists accessory_categories_write on public.accessory_categories;
create policy accessory_categories_write on public.accessory_categories
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));

drop policy if exists accessory_brands_select on public.accessory_brands;
create policy accessory_brands_select on public.accessory_brands
  for select to authenticated using (public.is_staff());
drop policy if exists accessory_brands_write on public.accessory_brands;
create policy accessory_brands_write on public.accessory_brands
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));

drop policy if exists accessory_suppliers_select on public.accessory_suppliers;
create policy accessory_suppliers_select on public.accessory_suppliers
  for select to authenticated using (public.is_staff());
drop policy if exists accessory_suppliers_write on public.accessory_suppliers;
create policy accessory_suppliers_write on public.accessory_suppliers
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));

drop policy if exists accessory_products_select on public.accessory_products;
create policy accessory_products_select on public.accessory_products
  for select to authenticated using (public.is_staff());
drop policy if exists accessory_products_write on public.accessory_products;
create policy accessory_products_write on public.accessory_products
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));

comment on table public.accessory_products is
  'Retail accessory stock sold at the counter. Separate from repair_parts (consumed in repairs). Stock only ever changes via direct edits here or sell_accessory_stock() at checkout.';
