-- ============================================================================
-- Mano Mobile — job receipt canvas templates
--
-- Mirrors 20260819000011_barcode_templates.sql + 20260819000012_label_canvas.sql,
-- for the printed job receipt instead of a barcode label. The receipt is a much
-- bigger canvas (an A5 landscape page, not a 50mm label) with a few element
-- kinds a label never needed — a QR code and the priced job-details table — but
-- the same idea: an ordered list of boxes placed in millimetres, some of them
-- containing {{tokens}} resolved per job at print time.
--
-- An empty `elements` array means "print the built-in JobReceiptSlip layout",
-- so this ships with zero rows and changes nothing until someone opens the
-- designer and builds one.
-- ============================================================================

create table if not exists public.receipt_templates (
  id               bigint generated by default as identity primary key,
  name             text not null unique,

  -- A5 landscape at 10mm margins ≈ 190 x 128mm of usable content area — see
  -- JobReceiptSlip's CONTENT_W. Stored rather than hard-coded so a future
  -- paper size doesn't need a migration, but every print caller still sets
  -- `@page { size: A5 landscape }` around this content.
  page_width_mm    numeric(6,2) not null default 190 check (page_width_mm > 0),
  page_height_mm   numeric(6,2) not null default 128 check (page_height_mm > 0),

  elements         jsonb not null default '[]'::jsonb,

  is_default       boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid references auth.users (id) on delete set null
);

do $$ begin
  alter table public.receipt_templates
    add constraint receipt_templates_elements_is_array
    check (jsonb_typeof(elements) = 'array');
exception when duplicate_object then null; end $$;

comment on column public.receipt_templates.elements is
  'Ordered receipt elements ({type,x,y,w,h,...} in mm). Empty array = print the built-in JobReceiptSlip layout.';

-- At most one default, same reasoning as barcode_templates_one_default: the
-- database refuses a second default outright instead of quietly fixing it up.
create unique index if not exists receipt_templates_one_default
  on public.receipt_templates (is_default) where is_default;

drop trigger if exists trg_receipt_templates_touch on public.receipt_templates;
create trigger trg_receipt_templates_touch
  before update on public.receipt_templates
  for each row execute function public.touch_updated_at();

-- ── Switching the default ───────────────────────────────────────────────────

create or replace function public.set_default_receipt_template(p_id bigint)
returns public.receipt_templates
language plpgsql
security definer
set search_path = public
as $$
declare
  tpl public.receipt_templates;
begin
  if not public.has_role('Admin'::staff_role, 'Cashier'::staff_role) then
    raise exception 'Not authorised to change the default receipt template';
  end if;

  update public.receipt_templates set is_default = false
   where is_default and id <> p_id;

  update public.receipt_templates set is_default = true
   where id = p_id
  returning * into tpl;

  if not found then
    raise exception 'Receipt template % not found', p_id;
  end if;

  return tpl;
end $$;

-- ── Row level security ──────────────────────────────────────────────────────

alter table public.receipt_templates enable row level security;

drop policy if exists receipt_templates_select on public.receipt_templates;
create policy receipt_templates_select on public.receipt_templates
  for select to authenticated using (public.is_staff());

drop policy if exists receipt_templates_write on public.receipt_templates;
create policy receipt_templates_write on public.receipt_templates
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));

comment on table public.receipt_templates is
  'Saved job-receipt designs. One row is is_default; empty elements = print the built-in JobReceiptSlip.';
