-- ============================================================================
-- SMS log (Text.lk gateway)
--
-- Every message the system sends is recorded: who sent it, to which number,
-- against which job, what it cost, and what the gateway said. SMS costs money
-- per message and is the shop's word to a customer, so "did we tell them?" and
-- "why were we charged for this?" both need an answer.
--
-- Rows are written by the server route (/api/sms/send) acting as the signed-in
-- user, never by the browser directly — the API token stays on the server.
-- ============================================================================

do $$ begin
  create type sms_status as enum ('Sent', 'Failed');
exception when duplicate_object then null; end $$;

create table if not exists public.sms_messages (
  id            bigint generated by default as identity primary key,

  -- Normalised to the gateway's format (94XXXXXXXXX), plus what was typed.
  recipient     text not null,
  recipient_raw text,
  sender_id     text not null,
  body          text not null,

  status        sms_status not null,
  -- Gateway's own id for the message, for chasing up a delivery query.
  provider_uid  text,
  provider_status text,
  cost          numeric(10,2),
  sms_count     integer,
  error         text,

  -- What this message was about. Nullable: not every SMS relates to a job.
  job_id        text references public.repair_jobs (id) on delete set null,
  purpose       text,

  sent_by       uuid references auth.users (id) on delete set null,
  sent_by_name  text,
  created_at    timestamptz not null default now()
);

create index if not exists sms_messages_job_idx     on public.sms_messages (job_id);
create index if not exists sms_messages_created_idx on public.sms_messages (created_at desc);
create index if not exists sms_messages_recipient_idx on public.sms_messages (recipient);

alter table public.sms_messages enable row level security;

-- Staff can read the log; nobody edits or deletes it — a sent message is a fact,
-- and an editable audit trail is not an audit trail.
drop policy if exists sms_select on public.sms_messages;
create policy sms_select on public.sms_messages
  for select to authenticated using (public.is_staff());

drop policy if exists sms_insert on public.sms_messages;
create policy sms_insert on public.sms_messages
  for insert to authenticated
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role, 'Technician'::staff_role));
