-- ============================================================================
-- Mano Mobile — the Warranty Center becomes a warranty lookup
--
-- The shop sells phones, accessories, gadgets and parts, and repairs devices,
-- and every one of those carries a warranty of its own kind. The Warranty
-- Center is now the place to answer one question for any of them: given an
-- invoice number, a job number, an IMEI or an item code — is it still covered?
--
-- Two gaps stood in the way.
--
-- ── 1. Repair warranties never started ──────────────────────────────────────
-- A repair warranty is issued when the job is finished, as "Pending
-- Activation", and its clock was meant to start at handover. The only thing
-- that started it was the Warranty Center's own handover dialog — the normal
-- checkout (Repair Sales / Issue Job) never did. So nearly every repair
-- warranty sat at Pending forever, with no start and no expiry.
--
-- Now the database starts it: the moment a job becomes Delivered, its pending
-- warranty is activated from the handover time. The ones already stuck are
-- activated below from when their job was handed over.
--
-- ── 2. Products had no warranty at all ──────────────────────────────────────
-- Phones, accessories and parts sold over the counter carried no warranty
-- record. warranty_policies says how long each kind is covered — with an
-- optional accessory category for finer rules (Chargers 90 days, Cases 0) —
-- and the lookup works the status out from the sale date. Seeded with
-- sensible defaults; change them in Warranty Center -> Policies.
-- ============================================================================

-- ── 1. Start repair warranties at handover ──────────────────────────────────

create or replace function public.tg_activate_warranty_on_delivery()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_start timestamptz;
begin
  if new.status = 'Delivered' and old.status is distinct from 'Delivered' then
    v_start := coalesce((new.handover ->> 'handedOverAt')::timestamptz, now());
    update public.warranties
       set status     = 'Active',
           starts_at  = v_start,
           expires_at = v_start + make_interval(days => duration_days)
     where job_id = new.id
       and status = 'Pending Activation';
  end if;
  return new;
end $$;

drop trigger if exists trg_activate_warranty_on_delivery on public.repair_jobs;
create trigger trg_activate_warranty_on_delivery
  after update of status on public.repair_jobs
  for each row execute function public.tg_activate_warranty_on_delivery();

-- The ones already stuck: activated from when their job was actually handed
-- over (the handover record, else the Delivered event, else the job's update).
update public.warranties w
   set status     = 'Active',
       starts_at  = s.start_at,
       expires_at = s.start_at + make_interval(days => w.duration_days)
  from (
    select j.id,
           coalesce(
             (j.handover ->> 'handedOverAt')::timestamptz,
             (select max(e.changed_at) from public.repair_job_events e
               where e.job_id = j.id and e.to_status = 'Delivered'),
             j.updated_at
           ) as start_at
      from public.repair_jobs j
     where j.status = 'Delivered'
  ) s
 where w.job_id = s.id
   and w.status = 'Pending Activation';

-- ── 2. Warranty policies for what is sold ───────────────────────────────────

create table if not exists public.warranty_policies (
  id            bigint generated by default as identity primary key,
  -- What it applies to: a phone, an accessory, a spare part, anything else.
  kind          text not null check (kind in ('device', 'accessory', 'part', 'other')),
  -- Optional finer rule — an accessory category ("Chargers"). Null is the
  -- default for the whole kind.
  category      text,
  duration_days integer not null default 0 check (duration_days >= 0),
  label         text not null default '',
  terms         text not null default '',
  updated_at    timestamptz not null default now()
);

create unique index if not exists warranty_policies_key
  on public.warranty_policies (kind, lower(coalesce(category, '')));

alter table public.warranty_policies enable row level security;

drop policy if exists warranty_policies_select on public.warranty_policies;
create policy warranty_policies_select on public.warranty_policies
  for select to authenticated using (public.is_staff());

drop policy if exists warranty_policies_write on public.warranty_policies;
create policy warranty_policies_write on public.warranty_policies
  for all to authenticated
  using (public.has_role('Admin'::staff_role) or public.is_admin_cashier())
  with check (public.has_role('Admin'::staff_role) or public.is_admin_cashier());

insert into public.warranty_policies (kind, category, duration_days, label, terms) values
  ('device',    null, 365, '1 year warranty',   'Manufacturing defects only. Physical, liquid and software damage are not covered.'),
  ('accessory', null, 30,  '1 month warranty',  'Replacement for factory defects within the period. Physical damage not covered.'),
  ('part',      null, 30,  '1 month warranty',  'Covers the part itself. Fitting by a third party voids it.'),
  ('other',     null, 0,   'No warranty',       '')
on conflict do nothing;

comment on table public.warranty_policies is
  'How long each kind of product sold is under warranty (device / accessory / part / other), optionally per accessory category. The Warranty Center works out a sale''s cover from these and the sale date.';
