-- ============================================================================
-- Mano Mobile — mobile device (phone) inventory, durable at last
--
-- Until now, InventoryManagement's Mobile Devices tab held its device list in
-- a plain useState([]) — gone on every refresh, invisible to every other
-- browser, never written to the database. This mirrors the accessory
-- inventory migration (20260903000001_accessory_inventory.sql) for a phone
-- instead of a retail accessory: same brand/supplier reference lists (shared
-- with accessories via useInventory(), not duplicated here), same RLS split,
-- same touch_updated_at trigger.
--
-- A device is sold and tracked one unit at a time (by IMEI), not as a
-- countable "stock" number the way accessory_products.stock is — so unlike
-- accessories there is no stock/min_stock pair or sell_*_stock() RPC here;
-- "status" (available/sold/reserved) already carries that.
-- ============================================================================

create table if not exists public.mobile_devices (
  id                bigint generated by default as identity primary key,
  imei              text not null,
  imei2             text not null default '',
  serial_number     text not null default '',
  -- The device's name/model, e.g. "Galaxy S21" — distinct from model_number
  -- below, which is the manufacturer's free-text model code on the box.
  name              text not null,
  model_number      text not null default '',
  brand             text not null default '',
  storage           text not null default '',
  ram               text not null default '',
  color             text not null default '',
  buying_price      numeric(12,2) not null default 0 check (buying_price >= 0),
  selling_price     numeric(12,2) not null default 0 check (selling_price >= 0),
  min_selling_price numeric(12,2) not null default 0 check (min_selling_price >= 0),
  supplier          text not null default '',
  status            text not null default 'available' check (status in ('available', 'sold', 'reserved')),
  notes             text not null default '',
  added_date        date not null default current_date,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  created_by        uuid references auth.users (id) on delete set null
);

-- IMEI is the primary identifier and stays unique per physical device. IMEI2
-- and serial_number are each unique too, but only when actually provided —
-- most devices won't have a second IMEI, and a plain unique constraint would
-- let empty strings collide and block every insert after the first.
create unique index if not exists mobile_devices_imei_key on public.mobile_devices (imei);
create unique index if not exists mobile_devices_imei2_key on public.mobile_devices (imei2)
  where imei2 is not null and imei2 <> '';
create unique index if not exists mobile_devices_serial_number_key on public.mobile_devices (serial_number)
  where serial_number is not null and serial_number <> '';

create index if not exists mobile_devices_brand_idx  on public.mobile_devices (brand);
create index if not exists mobile_devices_status_idx on public.mobile_devices (status);

drop trigger if exists trg_mobile_devices_touch on public.mobile_devices;
create trigger trg_mobile_devices_touch
  before update on public.mobile_devices
  for each row execute function public.touch_updated_at();

-- ============================================================================
-- Row Level Security — all staff read, Admin/Cashier write (devices are
-- stocked and sold at the counter, same split accessory_products uses).
-- ============================================================================

alter table public.mobile_devices enable row level security;

drop policy if exists mobile_devices_select on public.mobile_devices;
create policy mobile_devices_select on public.mobile_devices
  for select to authenticated using (public.is_staff());
drop policy if exists mobile_devices_write on public.mobile_devices;
create policy mobile_devices_write on public.mobile_devices
  for all to authenticated
  using (public.has_role('Admin'::staff_role, 'Cashier'::staff_role))
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role));

comment on table public.mobile_devices is
  'Mobile phone inventory tracked one unit at a time by IMEI. Separate from accessory_products (countable retail stock) — status (available/sold/reserved) carries what stock/min_stock does there.';
