-- ============================================================================
-- Mano Mobile — customer email
--
-- The shop already texts customers through Text.lk. Email adds the thing SMS
-- cannot carry: the job receipt itself, laid out, in something the customer
-- can keep and search for months later.
--
-- Four pieces, deliberately mirroring the SMS side so there is one pattern to
-- learn rather than two:
--
--   repair_jobs.customer_email   where to send (optional — most walk-ins have
--                                only a phone number, and that is fine)
--   email_settings               who it comes from, editable by Admin
--   email_templates              the wording, editable by Admin
--   email_messages               every attempt, so a lost email can be traced
--
-- Credentials are NOT here. The SMTP password is a spending credential and
-- lives in .env.local on the server, never in a table the browser can read.
-- ============================================================================

-- ── Where to send ───────────────────────────────────────────────────────────

alter table public.repair_jobs
  add column if not exists customer_email text;

comment on column public.repair_jobs.customer_email is
  'Optional. NULL means this customer gets SMS only, which is the normal case for a walk-in.';

-- ── Who it comes from ───────────────────────────────────────────────────────
-- A single row, like app_settings. The address is a setting rather than an env
-- var because the shop is starting on a personal address and will move to
-- their own domain later; that switch should not need a redeploy.

create table if not exists public.email_settings (
  id          boolean primary key default true check (id),

  from_name   text not null default 'Mano Mobile',
  from_email  text not null default '',
  -- Where customer replies go, when that differs from the sending address.
  reply_to    text,

  -- Master switch. Off, nothing is sent automatically and the templates screen
  -- says so — clearer than every message silently failing.
  enabled     boolean not null default false,

  updated_at  timestamptz not null default now(),
  updated_by  uuid references auth.users (id) on delete set null
);

comment on table public.email_settings is
  'Sending identity for customer email. Credentials live in server env, not here.';

insert into public.email_settings (id) values (true) on conflict (id) do nothing;

drop trigger if exists trg_email_settings_touch on public.email_settings;
create trigger trg_email_settings_touch
  before update on public.email_settings
  for each row execute function public.touch_updated_at();

-- ── What it says ────────────────────────────────────────────────────────────

create table if not exists public.email_templates (
  -- The lifecycle event this fires on: created | issued | finished.
  event       text primary key,
  name        text not null,
  subject     text not null,
  -- HTML. The renderer substitutes {placeholders} the same way SMS does, so an
  -- admin who has edited an SMS template already knows how this works.
  body        text not null,
  is_active   boolean not null default true,
  updated_at  timestamptz not null default now(),
  updated_by  uuid references auth.users (id) on delete set null
);

drop trigger if exists trg_email_templates_touch on public.email_templates;
create trigger trg_email_templates_touch
  before update on public.email_templates
  for each row execute function public.touch_updated_at();

-- ── What was sent ───────────────────────────────────────────────────────────

create table if not exists public.email_messages (
  id          bigint generated by default as identity primary key,
  to_address  text not null,
  subject     text not null,
  job_id      text references public.repair_jobs (id) on delete set null,
  purpose     text,
  -- 'sent' or 'failed'. Failures are recorded too: an email nobody received is
  -- exactly the thing you need a record of.
  status      text not null default 'sent',
  error       text,
  sent_at     timestamptz not null default now(),
  sent_by     uuid references auth.users (id) on delete set null
);

create index if not exists email_messages_job_idx  on public.email_messages (job_id);
create index if not exists email_messages_sent_idx on public.email_messages (sent_at desc);

-- ── Row level security ──────────────────────────────────────────────────────

alter table public.email_settings  enable row level security;
alter table public.email_templates enable row level security;
alter table public.email_messages  enable row level security;

-- Everyone sending needs to read the identity and the wording.
drop policy if exists email_settings_select on public.email_settings;
create policy email_settings_select on public.email_settings
  for select to authenticated using (public.is_staff());

drop policy if exists email_settings_admin_write on public.email_settings;
create policy email_settings_admin_write on public.email_settings
  for all to authenticated
  using (public.has_role('Admin'::staff_role)) with check (public.has_role('Admin'::staff_role));

drop policy if exists email_templates_select on public.email_templates;
create policy email_templates_select on public.email_templates
  for select to authenticated using (public.is_staff());

drop policy if exists email_templates_admin_write on public.email_templates;
create policy email_templates_admin_write on public.email_templates
  for all to authenticated
  using (public.has_role('Admin'::staff_role)) with check (public.has_role('Admin'::staff_role));

drop policy if exists email_messages_select on public.email_messages;
create policy email_messages_select on public.email_messages
  for select to authenticated using (public.is_staff());

drop policy if exists email_messages_insert on public.email_messages;
create policy email_messages_insert on public.email_messages
  for insert to authenticated
  with check (public.has_role('Admin'::staff_role, 'Cashier'::staff_role, 'Technician'::staff_role));

-- ── Default wording ─────────────────────────────────────────────────────────
-- Seeded once; `do nothing` so re-running never overwrites an edit.
--
-- 'created' and 'issued' are on: the receipt when the device is taken in, and
-- the record of collection when it goes back. 'finished' ships OFF because the
-- shop already texts that one — an admin can switch it on if they want both.

insert into public.email_templates (event, name, subject, body, is_active) values
('created', 'Job Receipt',
 'Your repair job {job_number} — Mano Mobile',
'<p>Hi {customer_name},</p>
<p>We have received your <strong>{device}</strong> for repair. Here are the details for your records.</p>
<table role="presentation" cellpadding="6" style="border-collapse:collapse;font-size:14px">
  <tr><td style="color:#666">Job Number</td><td><strong>{job_number}</strong></td></tr>
  <tr><td style="color:#666">Device</td><td>{device}</td></tr>
  <tr><td style="color:#666">IMEI</td><td>{imei}</td></tr>
  <tr><td style="color:#666">Fault</td><td>{fault}</td></tr>
  <tr><td style="color:#666">Estimated Price</td><td>{estimated_price}</td></tr>
  <tr><td style="color:#666">Paid Amount</td><td>{paid_amount}</td></tr>
  <tr><td style="color:#666">Due Amount</td><td>{due_amount}</td></tr>
  <tr><td style="color:#666">Technician</td><td>{technician}</td></tr>
</table>
<p>Please keep this email — the job number is what we use to find your device.</p>
<p>{shop_name}<br>{shop_phone}<br>{shop_address}</p>', true),

('issued', 'Device Collected',
 'Your {device} has been collected — {job_number}',
'<p>Hi {customer_name},</p>
<p>Your <strong>{device}</strong> has been collected. Thank you for choosing us.</p>
<table role="presentation" cellpadding="6" style="border-collapse:collapse;font-size:14px">
  <tr><td style="color:#666">Job Number</td><td><strong>{job_number}</strong></td></tr>
  <tr><td style="color:#666">Work Done</td><td>{fault}</td></tr>
  <tr><td style="color:#666">Final Bill</td><td>{estimated_price}</td></tr>
  <tr><td style="color:#666">Paid Amount</td><td>{paid_amount}</td></tr>
  <tr><td style="color:#666">Due Amount</td><td>{due_amount}</td></tr>
</table>
<p>If anything is not right with the repair, reply to this email or call us and we will look at it.</p>
<p>{shop_name}<br>{shop_phone}<br>{shop_address}</p>', true),

('finished', 'Ready For Collection',
 'Your {device} is ready to collect — {job_number}',
'<p>Hi {customer_name},</p>
<p>Good news — your <strong>{device}</strong> is repaired and ready to collect.</p>
<table role="presentation" cellpadding="6" style="border-collapse:collapse;font-size:14px">
  <tr><td style="color:#666">Job Number</td><td><strong>{job_number}</strong></td></tr>
  <tr><td style="color:#666">Final Bill</td><td>{estimated_price}</td></tr>
  <tr><td style="color:#666">Balance To Pay</td><td>{due_amount}</td></tr>
</table>
<p>{shop_name}<br>{shop_phone}<br>{shop_address}</p>', false)
on conflict (event) do nothing;
